services:
  goat-report:
    build: .
    container_name: goat_report_service
    restart: always
    environment:
      - GOAT_ID=${GOAT_TOKEN}
      - GOAT_KEY=${GOAT_KEY}
    volumes:
      - ./endpoints.json:/usr/src/app/endpoints.json
    command: ["python", "./goat_report.py"]

  endpoint-agent:
    build: .
    container_name: endpoint_agent_service
    restart: always
    environment:
      - ENDPOINTS_URL=https://raw.githubusercontent.com/1rabbit/goat_servers/refs/heads/main/uptime_endpoints
    volumes:
      - ./endpoints.json:/usr/src/app/endpoints.json
    command: ["python", "./endpoint_agent.py"]
