FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt goat_report.py endpoints.json ./

RUN pip install --no-cache-dir --only-binary=:all: --extra-index-url https://www.piwheels.org/simple -r requirements.txt

CMD ["python", "goat_report.py"]
