services:
  goat-report:
    image: ghcr.io/ducktatorrr/uptime-goat-node/goat-report:latest
    container_name: goat_report_service
    restart: always
    environment:
      - GOAT_ID=${GOAT_ID}
      - GOAT_KEY=${GOAT_KEY}
    volumes:
      - ./endpoints.json:/app/endpoints.json

  endpoint-agent:
    image: ghcr.io/ducktatorrr/uptime-goat-node/endpoint-agent:latest
    container_name: endpoint_agent_service
    restart: always
    environment:
      - ENDPOINTS_URL=${ENDPOINTS_URL}
    volumes:
      - ./endpoints.json:/app/endpoints.json
