FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt goat_report.py endpoints.json ./

RUN pip install --no-cache-dir --only-binary=:all: -r requirements.txt

CMD ["python", "goat_report.py"]
