FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir --only-binary=:all: --extra-index-url https://www.piwheels.org/simple -r requirements.txt

RUN chmod +x goat_report.py endpoint_agent.py start.sh

COPY endpoints.json /app/endpoints.json

CMD ["/bin/bash", "/app/start.sh"]
